# Generated by Django 4.2.3 on 2023-10-26 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_photo_album'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='slug',
        ),
    ]
